"""empty message

Revision ID: 013f911eb795
Revises: 
Create Date: 2021-02-12 16:42:47.265408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '013f911eb795'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=128), nullable=True),
    sa.Column('date_mod', sa.DateTime(), nullable=False),
    sa.Column('statut', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categorieplaylist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_musique', sa.String(length=200), nullable=True),
    sa.Column('statut', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historique',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('pseudonyme', sa.String(length=128), nullable=True),
    sa.Column('date_mod', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('internaute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_vis', sa.Integer(), nullable=True),
    sa.Column('date_mod', sa.DateTime(), nullable=False),
    sa.Column('date_vist', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promotion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom_promotion', sa.String(length=200), nullable=True),
    sa.Column('url', sa.String(length=200), nullable=True),
    sa.Column('date_debut', sa.Date(), nullable=True),
    sa.Column('date_fin', sa.Date(), nullable=True),
    sa.Column('statut', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=128), nullable=True),
    sa.Column('post_nom', sa.String(length=128), nullable=True),
    sa.Column('prenom', sa.String(length=128), nullable=True),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=128), nullable=True),
    sa.Column('password_onhash', sa.String(length=128), nullable=True),
    sa.Column('statut', sa.Boolean(), nullable=True),
    sa.Column('date_mod', sa.DateTime(), nullable=False),
    sa.Column('avatar', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('download',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_musique', sa.String(length=200), nullable=True),
    sa.Column('url_video', sa.String(length=200), nullable=True),
    sa.Column('id_internaute', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_internaute'], ['internaute.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=True),
    sa.Column('categoriePlaylist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoriePlaylist_id'], ['categorieplaylist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=True),
    sa.Column('resume', sa.Text(), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('statut', sa.Boolean(), nullable=True),
    sa.Column('url_img', sa.String(length=128), nullable=True),
    sa.Column('date_pub', sa.DateTime(), nullable=False),
    sa.Column('date_mod', sa.DateTime(), nullable=False),
    sa.Column('nbr_lu', sa.Integer(), nullable=True),
    sa.Column('nbr_like', sa.Integer(), nullable=True),
    sa.Column('nbr_cmt', sa.Integer(), nullable=True),
    sa.Column('categorie_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categorie_id'], ['categorie.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commentaire',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('statut', sa.Boolean(), nullable=True),
    sa.Column('primaire', sa.Boolean(), nullable=True),
    sa.Column('secondaire', sa.Boolean(), nullable=True),
    sa.Column('id_primaire', sa.Integer(), nullable=True),
    sa.Column('date_mod', sa.DateTime(), nullable=False),
    sa.Column('publication_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['publication_id'], ['publication.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fichier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_img', sa.String(length=128), nullable=True),
    sa.Column('url_pdf', sa.String(length=128), nullable=True),
    sa.Column('date_mod', sa.DateTime(), nullable=False),
    sa.Column('publication_id', sa.Integer(), nullable=False),
    sa.Column('promotion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotion.id'], ),
    sa.ForeignKeyConstraint(['publication_id'], ['publication.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_publication', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_publication'], ['publication.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('statut', sa.Boolean(), nullable=True),
    sa.Column('date_mod', sa.DateTime(), nullable=False),
    sa.Column('commentaire_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['commentaire_id'], ['commentaire.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    op.drop_table('like')
    op.drop_table('fichier')
    op.drop_table('commentaire')
    op.drop_table('publication')
    op.drop_table('playlist')
    op.drop_table('download')
    op.drop_table('user')
    op.drop_table('promotion')
    op.drop_table('internaute')
    op.drop_table('historique')
    op.drop_table('categorieplaylist')
    op.drop_table('categorie')
    # ### end Alembic commands ###
